# Generated by Django 5.2.17 on 2026-08-16 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_reference', models.CharField(blank=True, max_length=64)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('age', models.PositiveIntegerField()),
                ('emergency_type', models.CharField(choices=[('CARDIAC', 'Cardiac'), ('TRAUMA', 'Trauma'), ('RESPIRATORY', 'Respiratory'), ('STROKE', 'Stroke'), ('OTHER', 'Other')], max_length=32)),
                ('reported_conditions', models.JSONField(blank=True, default=list)),
                ('vital_data', models.JSONField(blank=True, default=dict)),
                ('ai_risk_score', models.FloatField(blank=True, null=True)),
                ('ai_priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16, null=True)),
                ('verified_priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('AMBULANCE_ASSIGNMENT', 'Ambulance Assignment'), ('HOSPITAL_SELECTION', 'Hospital Selection'), ('HOSPITAL_PENDING', 'Hospital Pending'), ('DISPATCHED', 'Dispatched'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('HANDOVER', 'Handover'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emergencies', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_emergencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'emergencies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('EMERGENCY_CREATED', 'Emergency Created'), ('EMERGENCY_VERIFIED', 'Emergency Verified'), ('AMBULANCE_ASSIGNED', 'Ambulance Assigned'), ('HOSPITAL_RECOMMENDED', 'Hospital Recommended'), ('STATUS_CHANGED', 'Status Changed')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_events', to=settings.AUTH_USER_MODEL)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='emergencies.emergency')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
