# Generated by Django 5.2.17 on 2026-08-16 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='rejected_hospital_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emergency',
            name='selected_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_emergencies', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='emergencyevent',
            name='event_type',
            field=models.CharField(choices=[('EMERGENCY_CREATED', 'Emergency Created'), ('EMERGENCY_VERIFIED', 'Emergency Verified'), ('AMBULANCE_ASSIGNED', 'Ambulance Assigned'), ('HOSPITAL_RECOMMENDED', 'Hospital Recommended'), ('HOSPITAL_SELECTED', 'Hospital Selected'), ('HOSPITAL_ALERT_SENT', 'Hospital Alert Sent'), ('HOSPITAL_ALERT_ACKNOWLEDGED', 'Hospital Alert Acknowledged'), ('HOSPITAL_PREPARATION_STARTED', 'Hospital Preparation Started'), ('HOSPITAL_READY', 'Hospital Ready'), ('HOSPITAL_NOT_READY', 'Hospital Not Ready'), ('HOSPITAL_RESPONSE_TIMEOUT', 'Hospital Response Timeout'), ('HOSPITAL_REASSIGNED', 'Hospital Reassigned'), ('ROUTE_OPTIMIZED', 'Route Optimized'), ('ROUTE_CHANGED', 'Route Changed'), ('AMBULANCE_LOCATION_UPDATED', 'Ambulance Location Updated'), ('HANDOVER_STARTED', 'Handover Started'), ('HANDOVER_SUBMITTED', 'Handover Submitted'), ('HANDOVER_ACCEPTED', 'Handover Accepted'), ('HANDOVER_COMPLETED', 'Handover Completed'), ('STATUS_CHANGED', 'Status Changed')], max_length=32),
        ),
    ]
