# Generated by Django 5.2.17 on 2026-08-16 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulances', '0001_initial'),
        ('emergencies', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='ambulances.ambulance')),
                ('dispatcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to=settings.AUTH_USER_MODEL)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='emergencies.emergency')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
