# Generated by Django 5.2.17 on 2026-08-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('LIMITED', 'Limited'), ('CLOSED', 'Closed')], default='OPERATIONAL', max_length=16)),
                ('emergency_department_status', models.CharField(choices=[('OPEN', 'Open'), ('OVERCROWDED', 'Overcrowded'), ('DIVERT', 'Divert')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('ICU_BED', 'ICU Bed'), ('EMERGENCY_BED', 'Emergency Bed'), ('VENTILATOR', 'Ventilator'), ('OXYGEN', 'Oxygen'), ('OPERATING_ROOM', 'Operating Room'), ('SPECIALIST', 'Specialist')], max_length=32)),
                ('total', models.PositiveIntegerField(default=0)),
                ('available', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='hospitals.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'resource_type')},
            },
        ),
    ]
