# Generated by Django 5.2.17 on 2026-08-16 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_emergency_rejected_hospital_ids_and_more'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=16)),
                ('eta', models.FloatField(help_text='Estimated time of arrival in minutes')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('NOT_READY', 'Not Ready'), ('RESPONSE_TIMEOUT', 'Response Timeout'), ('CANCELLED', 'Cancelled')], default='SENT', max_length=32)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('readiness_checklist', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('preparation_started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('not_ready_at', models.DateTimeField(blank=True, null=True)),
                ('not_ready_reason', models.TextField(blank=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_alerts', to='emergencies.emergency')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hospitals.hospital')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_alerts_responded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
