# Generated by Django 5.2.17 on 2026-08-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=32, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=16)),
                ('capability_level', models.CharField(choices=[('BASIC', 'Basic'), ('ADVANCED', 'Advanced'), ('CRITICAL_CARE', 'Critical Care')], default='BASIC', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_emergency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ambulances', to='emergencies.emergency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='accounts.organization')),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='ambulances.ambulance')),
            ],
            options={
                'verbose_name_plural': 'ambulance equipment',
                'unique_together': {('ambulance', 'equipment_name')},
            },
        ),
    ]
