# Generated by Django 5.2.17 on 2026-08-16 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulances', '0001_initial'),
        ('emergencies', '0002_emergency_rejected_hospital_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('baseline', 'Baseline'), ('intelligent', 'Intelligent')], max_length=16)),
                ('node_ids', models.JSONField(default=list)),
                ('edge_ids', models.JSONField(default=list)),
                ('route_nodes', models.JSONField(default=list)),
                ('route_edges', models.JSONField(default=list)),
                ('total_distance_km', models.FloatField()),
                ('estimated_time_min', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='ambulances.ambulance')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='emergencies.emergency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('base_travel_time_min', models.FloatField()),
                ('traffic_factor', models.FloatField(default=1.0)),
                ('current_travel_time_min', models.FloatField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='routes.roadnode')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='routes.roadnode')),
            ],
            options={
                'unique_together': {('source', 'destination')},
            },
        ),
    ]
